### ISSUE TITLE
expected checksums of patched roms

### ISSUE THREAD

**Issue by tjanas** [jombo23/N64-Tools#10]
Could you provide checksum information on the source roms and expected checksum after patching? For example, I am curious about "Bomberman 64 - Arcade Edition (J) Translated 1_2 Analog.xdelta".  I have a BigEndian "Bomber Man 64 (Japan)" rom with CRC32=7E74EEDC, and when patched with the v1.2 translation patch [here](https://www.romhacking.net/translations/2755/), that resulting rom is CRC32=9BB224CA.

Is the translation-patched rom with CRC32=9BB224CA the correct input rom to use with "Bomberman 64 - Arcade Edition (J) Translated 1_2 Analog.xdelta"?

If so, is CRC32=4F333DF6 the correct result after appling this Translated 1_2 Analog patch against the translated rom?

**Comment by SubDrag** [comment]
The CRC32 of 1.2 Translation is 9bb224ca.  So yours seems right.  After analog controls it's 4f333df6 which matches.    It should work fine then.
