### ISSUE TITLE
Can't start N64 Soundbank Tool

### ISSUE THREAD

**Issue by SamusAranX** [jombo23/N64-Tools#11]
Every time I try to start it, I get this error message:
> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

I'm using an up-to-date copy of Windows 10. What gives?

**Comment by SamusAranX** [comment]
Turns out I was missing the redistributables. It'd be great if prerequisites like this were mentioned in the readme.

**Comment by SubDrag** [comment]
OK I added, they are here:
https://github.com/jombo23/N64-Tools/tree/master/Redistributables
