### ISSUE TITLE
Custom Goldeneye Rom Hacks crashed in Soundbank Tool

### ISSUE THREAD

**Issue by Mikantsumikiwi** [jombo23/N64-Tools#12]
Hey guys, i been trying to rip custom instruments i made for a goldeneye rom and i can't seem to access the dls as it tend to crash the program in fact. 

For example Perfect Dark can rip the dls soundbank just fine when they have custom samples included,

For goldeneye in the other hand, it crashes even when i selected the correct region that it was aiming for in terms of it rom. 

It not just the rom hacks that have custom samples, it also the custom rom hacks themselves when i was testing it and i am reporting this because i kinda want to rip my custom samples for the game without having issues at all. 

I never have this issue with Perfect Dark in terms of testing the custom soundbank i made for it.

**Comment by SubDrag** [comment]
Unfortunately yeah GoldenEye ROMs from GoldenEye Setup Editor shift the data, which isn't accounted for by hardcoded offsets using this simplistic tool.  But the GoldenEye Setup Editor can't export DLS because of GPL restrictions on the original code I used.  You would have to find the spots in this tool and temporarily update the ini.   I don't even know any ROM hacks with custom samples.  Is there something specific you're trying to do or a specific mod that you really need this for?

**Comment by Mikantsumikiwi** [comment]
> Unfortunately yeah GoldenEye ROMs from GoldenEye Setup Editor shift the data, which isn't accounted for by hardcoded offsets using this simplistic tool. But the GoldenEye Setup Editor can't export DLS because of GPL restrictions on the original code I used. You would have to find the spots in this tool and temporarily update the ini. I don't even know any ROM hacks with custom samples. Is there something specific you're trying to do or a specific mod that you really need this for?

I am doing this for a mod called The Living Daylights 64, the director decided to give us the freedom to use custom samples in the game and we have tested them in game and they actually worked in fact. 

Mostly we wanted to extract the DLS in the soundbank tool and test the samples to make sure they are pitch correctly or in the same volume rate as the original sound. 

Overall thank you for responding to my issue.

**Comment by SubDrag** [comment]
OK I updated the N64 Soundbank/Sound tool to support the dynamic address nature of GoldenEye US version.  Since the editor does that, and it's one I know about and easy to handle, I did.  Hopefully that helps.  Give it a try.

**Comment by Mikantsumikiwi** [comment]
> OK I updated the N64 Soundbank/Sound tool to support the dynamic address nature of GoldenEye US version. Since the editor does that, and it's one I know about and easy to handle, I did. Hopefully that helps. Give it a try.

Hey there, i tested the update on a custom rom for the mod i am working on with other folks and i have to say it really works and now it don't crash at all when testing it. 

Thank you for this helpful update as lately the soundfont editors i been using are inaccurate in terms of the samples for GE and often change the pitch as well. 

Thankfully i don't need to worry about the SF2 editors now due to this update now. 

Regardless, this have been a extremely useful update.
