### ISSUE TITLE
Undetected Zelda64 Banks in Soundbank Tool

### ISSUE THREAD

**Issue by isghj5** [jombo23/N64-Tools#13]
In Majora's Mask U Bank 0x01 is missing from the discovered banks.

In OOT U 1.0 banks 0x01 and 0x02 are missing.

Maybe these banks aren't used by their vanilla games for music but they could prove useful for building custom music where sound effects are needed as instruments.

If possible, could these banks be detected for creation of soundfonts?

Edit: I think I successfully extracted MM:0x01 by using Seq64 copying bank 01 onto 00 then ripping 00, in case anyone else wants these banks

**Comment by SubDrag** [comment]
Not sure what you mean? It should match all the known banks of both games.  How do you know they are missing? What is their offset?

**Comment by isghj5** [comment]
I know it's missing because it's not there in the drop down list of banks and does not extract if you write all banks.

I know it exists because in Seq64 you can point sequences at the bank and play instruments there, and you can rip instruments from bank 01 to use in custom instrument sets. As per my edit, you can also use Seq64 to write bank 01 to bank 00 and use the soundbank tool to rip it as a soundfont.

My guess is it isn't detected as a bank because its not used by any sequence, its just sound effects, not actual instruments used in a song.

[Picture of missing bank](https://mega.nz/file/6aoxDLRa "Picture of missing bank") 

music made with the soundfont, and it plays with the instrument in a custom bank in-game: https://mega.nz/file/zG4F3Zga

**Comment by SubDrag** [comment]
Oh you're talking about the soundbank tool.  So, the only soundbanks there are ones mapped to a song.  I suppose I can add them, in the gameconfig.ini, it maps soundbank to midi, so I guess we can add those back.
[Legend of Zelda, The - Ocarina of Time (U) (V1.0)]
{SamplingRate:32000}
00:44,45,46,47,48,49
03:02,03,04,05,06,07,08,09,0A,0B,0C,0D,0E,0F,10,11,12,13,14,15,16,17,19,1A,1B,1F,21,23,2B,2D,31,32,38,3B,43,4A,51,52,53,54,62,6C
04:1C
...

**Comment by SubDrag** [comment]
I uploaded a new gameconfig.ini that has those in there that you reported (01/02 OoT, 01 MM).  They will show all midis.
