### ISSUE TITLE
Audio glitches when replacing Instru_0046 and Instru_003F in Goldeneye setup editor

### ISSUE THREAD

**Issue by Mikantsumikiwi** [jombo23/N64-Tools#14]
Hey there, these two instruments have caused some certain audio distortion and static when i replaced them, even if i actually put the instruments back in it still contain the glitchy sounds and etc. 

Thanks to your helpful update i was enable to use my sounds in goldeneye via DLS, through i been experiencing these strange glitches when replacing two certain instruments even if i actually put the sounds in there correct pitch. 

When i test the sounds in goldeneye itself it cause me some strange glitches while the dls itself is fine and plays the sounds perfectly. 

When testing the samples ingame, by these two presets that sorta cause certain audio glitches to goldeneye itself, i never have this issue when replacing certain sounds in Perfect Dark but seem like goldeneye is pretty glitchy.

I can provide and share a Xdelta link if anyone is willing to actually can see and analyzed what causing the strange audio glitches.

Unless, i am doing something wrong here i do apologize for reporting this issue in here. 

Since i am really new to this stuff.

**Comment by SubDrag** [comment]
Is it only two instruments, or all instruments?  There are two raw sounds in GoldenEye.

**Comment by Mikantsumikiwi** [comment]
Well, actually based on experience these are the only two instruments that cause me certain issues.

When they go in the highest pitch, it sounds really messed up and i been using the raw .wav option for them overall, in a sense i been using the normal GE rom to convert these in fact. 

While it sounds perfectly fine in the dls and the editor itself yes, but when used ingame instru_0046 sounds perfect fine in the lowest or medium pitch when it goes in the highest octave it sounds pretty corrupt while i have edit these instruments a few times. 

The same problem issue occurs.

These are the list of the instruments that have sounded pretty fine when imported.

Instru_05
instru_12 
Instru_3E 
Instru_40
Instru_0E 
instru_003B 


I guess, i should used VADPCM to fix the problem.

Considering i have a feeling the raw wav option is not really recognizing the string instruments properly.

I do have a recording of me testing the string sounds i imported.

https://drive.google.com/file/d/1OVSlroDb3ge8-4Zlu4oZIQxRWsHC1kWr/view?usp=sharing

I might try editing the parameters through.

**Comment by SubDrag** [comment]
That sounds parameter related - you probably want to tweak the key ranges and such, to make the instruments hit the ranges you want.

**Comment by Mikantsumikiwi** [comment]
i know something is not right, overall i am going to adjust the sounds when i can. 

Thanks for the feedback!
