### ISSUE TITLE
Sound tool can't find ordinal 7312 within its own application file

### ISSUE THREAD

**Issue by superminerJG** [jombo23/N64-Tools#15]
Self-explanatory. I have all the VC++ redists needed. The dialog shows the following:

... could not find ordinal 7312 in _C:\path\to\cloned-repo\N64-Tools\N64 Sound Tool\N64SoundListToolUpdated\Release\N64SoundListTool.exe_

**Comment by SubDrag** [comment]
That's a redistributable issue.  You must not have the right one.    VS2008 SP1 for that one.
https://github.com/jombo23/N64-Tools/blob/master/Redistributables/vcredist_x86_vs2008.exe
