### ISSUE TITLE
Gex 64 don't export all of the midi files in midi tool.

### ISSUE THREAD

**Issue by Mikantsumikiwi** [jombo23/N64-Tools#16]
I don't think i should count as a issue but more of a suggestion, actually i could extract the soundfonts very well but i been wanting to extract all of the midi files for Gex 2 on the n64. 

Instead of giving me all of the midi files, it just only give me the jingles that are played in game instead. 

I only have total of all 7 midi tracks that are commonly jingles when you either died or a game over and etc.

I wonder if there is a way to update the Gex 64 midi extractions to all of the tracks unless it complicated to understand it's code. 

I know a similar issue occurs with perfect dark which only give you around 70 midis or so instead of 119. 

It later on got fixed. 

Overall just reporting this, mainly i can rip all of Gex 3 midis just fine.

**Comment by SubDrag** [comment]
There's two sets, are you loading the other set too? The other one has a different name, cause different format, not compressed.

[Gex 64 - Enter the Gecko (U) ZLib]:type=ZLibSng
003EB590,003EC2A0
00401F70,00402880
00402880,004030B0
004030B0,00403DD0
00403DD0,00405C60
00405C60,004066F0
0041B390,0041CA80
0041CA80,0041CE00
00439330,0043B180
00457A80,00458B70
00458B70,00459FF0
00459FF0,0045A5C0
0045A5C0,0045AE70
0045AE70,0045B420
0045B420,0045CBC0
0045CBC0,0045D100
0045D100,0045D6D0
0045D6D0,0045DC50
0047A340,0047B670
0047B670,0047CCB0
00490EC0,004918E0
004918E0,004931C0
004931C0,004958F0
[Gex 64 - Enter the Gecko (U)]:type=Sng
00497E00,00498300
00498300,00498A50
00498A50,00499550
00499550,0049A1F8

**Comment by Mikantsumikiwi** [comment]
Thank you, i finally figure it out.
