### ISSUE TITLE
Inject in place: error, ctl too big

### ISSUE THREAD

**Issue by jpleau** [jombo23/N64-Tools#18]
Using N64SoundListTool.exe, if I try to open a known game (Mario Tennis (U)), I select my rom file. If I press "Inject in-place" I get this error:

`Error ctl too big, 18C90 is too big for 18A38`

This is without changing anything, just open the rom and click on Inject.

Is there something I can do to work around this?

Thanks

**Comment by SubDrag** [comment]
I guess unfortunately the regeneration somehow wasn't an optimal...The only way would be to kind of import empty predictors to unused sounds or remove loops or different ways to shrink the file.  That's strange, I thought my import was pretty decent.

**Comment by SubDrag** [comment]
Apparently I forgot to include "Fine Tones" in the ctl size.  It now yields the correct size and you can inject in latest version, give it a try.

**Comment by jpleau** [comment]
Yep it now works, thanks!
