### ISSUE TITLE
Channels are not ordered in the additional parts

### ISSUE THREAD

**Issue by Sozuke** [jombo23/N64-Tools#19]
For example puyo 4 or disney dancing museum

the main midi has the channels separated by instruments, but the additional parts are still maintained as instrument change events on the channels

**Comment by SubDrag** [comment]
Do you have an example? I checked out puyo 4 song 1 and it still looks sorted in the additional part, when Separate by Instrument is checked.

**Comment by SubDrag** [comment]
OK found an example (Disney, Song 1).  It happened for notes that were overlapping when split up.  Try the new version, now it adds additional tracks to preserve the separation.
