### ISSUE TITLE
Not working on 64-bit

### ISSUE THREAD

**Issue by MasterNama2008** [jombo23/N64-Tools#21]
Why still pop up error message?
I'm running on windows 10 and 64-bit
![image](https://user-images.githubusercontent.com/71924055/105851740-7ba03080-6009-11eb-9a8a-f65d7658f87f.png)

**Comment by SubDrag** [comment]
You need to install the VS2008 32-bit MFC C++ redistributable.

**Comment by SubDrag** [comment]
https://github.com/jombo23/N64-Tools/blob/master/Redistributables/vcredist_x86_vs2008.exe
