### ISSUE TITLE
Side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by mariofan12ify** [jombo23/N64-Tools#23]
Having trouble opening any of the tools because this error keeps showing up. Any way to fix?
![image](https://user-images.githubusercontent.com/35483921/109377919-519aa080-791e-11eb-9b9c-fa9a774b3653.png)

**Comment by SubDrag** [comment]
Install all of these:
https://github.com/jombo23/N64-Tools/tree/master/Redistributables
