### ISSUE TITLE
EAD Games Missing Release Rate

### ISSUE THREAD

**Issue by L-Spiro** [jombo23/N64-Tools#27]
I don’t believe this is a Seq64 issue because as far as I can tell Seq64 provides the release rates for games, they simply aren’t being used.

Taking Star Fox 64 as an example, bank 1D has the following release rates on instruments 0x00-0x05:
71, 133,  86,  29,  95,  48
And for 0x7F (percussion) it is:
53

But when we look inside ExtractedSoundbank_1D.dlsDebug.txt, all of the regular samples have a release of FB500000 and the percussion has F06DAFB6.
I haven’t been able to get Seq64 to do anything useful and spit out the release rates, but it seems to acknowledge that they exist, so I am just assuming it is actually spitting these values out when someone actually knows how to use it, so I am currently under the assumption that this is an issue that needs to be addressed on this end.
![image](https://user-images.githubusercontent.com/7362666/136868263-7e96b58f-c550-49ae-984e-fdb9b32b792e.png)

Since Seq64 V1 is no longer being updated, it really has to be handled on this end or else it just won’t be handled at all, in any case.  Can this get fixed on this end?

**Comment by L-Spiro** [comment]
I e-mailed Sauraen before creating this issue.
The point is, however, that I believe Seq64 is giving you the release rates and you are just not using them.

Just as I had requested the ADSR values be part of the debug export, can you add the release rates to the debug export?  The DLS/SoundFont data is useless to me, and I don’t want to be missing out on release rates just because some other data I am not even using doesn’t support it correctly.

Also, I have decoded them, so if you would like to support them properly in DLS I can pass the information along.
The values are simply the speeds at which the sound linearly decays upon release, so larger values equate to shorter release times.

Here is example code for Super Mario 64:

```
	double AdsrReleaseRateToTime( uint8_t _ui8Rate, uint32_t _ui32Hz ) {
		const int32_t gAiFrequency = _ui32Hz;
		const int32_t gSamplesPerFrameTarget = ((gAiFrequency / 60) + 0xF) & ~0xF;
		const int32_t updatesPerFrame = gSamplesPerFrameTarget / 160 + 1;
		double dTime = 0x8000 / (((_ui8Rate * 24.0)) * updatesPerFrame) / 60.0;
		return dTime;
	}
	…
double dTime = AdsrReleaseRateToTime( RELEASERATE, SAMPLERATE /* Usually 32000. */ );
const double dSlowSpeed = 3.0;
const double dFastSpeed = 5.0;
const double dSlowPoint = 10.0;
const double dFastPoint = 208.0;
const double dDiff = (dFastPoint - dSlowPoint);
const double dFinal = ((RELEASERATE - dSlowPoint) / dDiff)  * (dFastSpeed - dSlowSpeed) + dSlowSpeed;
```
dFinal is the release time in seconds.
Multiply by 3.5 for other EAD games.


I would like to request that the debug TXT files contain the proper release rates, just as they contain the ADSR data.

**Comment by SubDrag** [comment]
Not sure where that code is to be applied.   I seem to be outputting in debug the 8 ADSR 16-bit constants.  
https://github.com/jombo23/N64-Tools/blob/master/N64%20Soundbank%20Tool/N64SoundbankToolDlg.cpp#L1074

**Comment by SubDrag** [comment]
Where is that 71 coming from?

**Comment by L-Spiro** [comment]
In Mario Kart 64 the release rate is right after the splits.  Can you find this in whatever data you read?
![image](https://user-images.githubusercontent.com/7362666/136875914-e2f987ee-2477-4521-a421-4f6b16bfacad.png)

**Comment by SubDrag** [comment]
The real data doesn't look like that - splits are floating point?

For example, Star Fox 1.1, 0x0011BD10 is the first instrument.  0x20 bytes per.  
![image](https://user-images.githubusercontent.com/4073825/136876067-07c1620f-7a25-41d8-a836-598be6ccb532.png)

The splits are floating points...0xC, 0x14, 0x1C offsets.  I don't know where he is pulling is data, you will have to find me the real data in ROM.

**Comment by L-Spiro** [comment]
N64-Tools-master\N64 Soundbank Tool\Release\romdesc\Mario Kart 64 (U).xml
This file defines that structure.  I don’t know how this file relates to your tool, but it should at least provide a hint, and it is included with your tool.


Splits are 3 floating-point values.  That’s what `ABSound splits[0x3];` is.  That’s not “splitpoint1” and “splitpoint2.”


Look, you have the release rates **right there**:
![image](https://user-images.githubusercontent.com/7362666/136876998-a047b093-6e82-4ee2-8030-32581dcace0d.png)
See that “Splits/RelTime” value?
(0x00007F64 & 0xFF) = 100
![image](https://user-images.githubusercontent.com/7362666/136877075-32b2bdca-91ad-4770-874d-49c2de2a1371.png)
(0x00007F35 & 0xFF) = 53
![image](https://user-images.githubusercontent.com/7362666/136877132-a2379703-9122-4012-ba81-5481bbfb4300.png)
(0x00007F64 & 0xFF) = 100
Bank 15 release times are:
100,  53,  XX, 100, 100,  95, 100,  XX,  10,  XX,  81,  62, 114,  XX,  90, 142

That’s literally the data right there that I want to be exported into the debug TXT file!
