### ISSUE TITLE
Sample Level Not Always Exported into Debug SoundBank TXT

### ISSUE THREAD

**Issue by L-Spiro** [jombo23/N64-Tools#28]
Open Super Robot Spirits in **N64 Soundbank Tool**.
Check **Debug**.
Press **Write All DLS Soundfont Banks**.
Export to any folder.
Open the created file, **ExtractedSoundbank_00.dlsDebug.txt**.
Notice that Instrument 04 correctly reflects the Sample Vol value:
**Sample Vol** = **6E** and **73**, debug file contains **Attenuation 03320D13** and **Attenuation 03128978**.
Now look at Instrument 06, which has **Sample Vol** = **55**, but the debug file has **Attenuation 00000000**.
Debug file should contain **Attenuation 0383E26E** here.

**Comment by jombo23** [comment]
Just to be clear, youre referring to https://github.com/jombo23/N64-Tools/blob/master/N64%20Soundbank%20Tool/N64SoundbankToolDlg.cpp#L1710 ?

**Comment by L-Spiro** [comment]
I am referring to the debug line that looks like this (example taken from Instrument 0C since that happens to be on my screen at the moment):
Key Base 35 Fine Tune FFFFFFEB Volume **Attenuation 00000000**

Within the same export, sometimes it is correct, other times it is not.

What you posted is one of the lines of code that prints the above debug line, but I can’t say whether it is the exact section of code that has this bug.  I expect that the bug is there in all sections that print that debug text.

**Comment by L-Spiro** [comment]
The steps to reproduce the issue are in the first post.
Super Robot Spirits.
```
Instrument 04
[Not in DLS] Bend Range C8
Number Sounds 0004
Sound 0000
Sampling Rate 22050.000000
Attack 80000000 Decay 000236E8 Sustain 03E80000 Release F6A236E5 (Attack Volume 7F Decay Volume 7F)
Pan 60 (00FFE7CF)
Key Base 30 Fine Tune 0000 Volume Attenuation 03320D13
Key Low 1F Key High 20 Vel Low 00 Vel High 7F
Sound 0001
Sampling Rate 22050.000000
Attack 80000000 Decay 000236E8 Sustain 03E80000 Release F6A236E5 (Attack Volume 7F Decay Volume 7F)
Pan 54 (00A16AD4)
Key Base 30 Fine Tune 0000 Volume Attenuation 03320D13
Key Low 21 Key High 21 Vel Low 00 Vel High 7F
Sound 0002
Sampling Rate 22050.000000
Attack 80000000 Decay 000236E8 Sustain 03E80000 Release F6A236E5 (Attack Volume 7F Decay Volume 7F)
Pan 7F (01F40000)
Key Base 30 Fine Tune 0000 Volume Attenuation 03128978
Key Low 23 Key High 27 Vel Low 00 Vel High 7F
Sound 0003
Sampling Rate 22050.000000
Attack 80000000 Decay 000236E8 Sustain 03E80000 Release F6A236E5 (Attack Volume 7F Decay Volume 7F)
Pan 54 (00A16AD4)
Key Base 30 Fine Tune 0000 Volume Attenuation 03128978
Key Low 28 Key High 7F Vel Low 00 Vel High 7F
```
This is correct.

```
Instrument 06
[Not in DLS] Bend Range C8
Number Sounds 0001
Sound 0000
Sampling Rate 22050.000000
Attack 80000000 Decay 7FFFFFFF Sustain 03E80000 Release F6A00000 (Attack Volume 7F Decay Volume 7F)
Loop Count 00000001 Start 00000EDC Length 000003F4
Key Base 30 Fine Tune 0000 Volume Attenuation 00000000
Key Low 00 Key High 7F Vel Low 00 Vel High 7F
```
This is not correct.
It should have printed _Key Base 30 Fine Tune 0000 Volume **Attenuation 0383E26E**_.

It printed instrument 4 correctly and it did not print instrument 6 correctly.  Correct prints and incorrect prints are spread throughout the file randomly.  When an **Sample Vol** is not 0x7F, sometimes it prints the value correctly and other times it does not.

**Comment by L-Spiro** [comment]
It is in a few places.  In all places it is a bug.  It’s saying that if a sample has no decay, then it must play at full volume.  That’s bizarre and incorrect.  All copies of that line should be removed and then the exports will be one step closer to complete.
Getting the Instrument Vol exported would be another good step, and adding the release rate next to the ADSR values in my other open issue would be the final step.  These 3 things make a fully complete set of debug exports.

**Comment by jombo23** [comment]
Im sure there is some reason for it, however, since this is open source youre more than welcome to modify it, demonstrate it actually being proper under all cases, and then submit a pull request. That is, unless subdrag has anything to add.

**Comment by jombo23** [comment]
Instrument 06
[Not in DLS] Bend Range C8
Number Sounds 0001
Sound 0000
Sampling Rate 22050.000000
Attack 80000000 Decay 7FFFFFFF Sustain 03E80000 Release F6A00000 (Attack Volume 7F Decay Volume 7F)
Loop Count 00000001 Start 00000EDC Length 000003F4
Key Base 30 Fine Tune 0000 Volume Attenuation 0383E26E
Key Low 00 Key High 7F Vel Low 00 Vel High 7F

**Comment by jombo23** [comment]
This only fixed a couple instances. Theres apparently more going on here or im bad at reading x86. Going to edit a couple more things just for giggles and see where it ends up.

**Comment by jombo23** [comment]
I think this might be as i suspected. @L-Spiro What are the chances of only *some* of the instruments with decays of -1 having attenuation values? I cleared just about everything I could find and it fixed a handful of instruments (instrument 6 is now filled in while instrument C isnt for ex). Is its something where theres a default if the value is 0? Im kinda lost.

Heres the build with the decay check/s patched out. This comes with absolutely ZERO support as the binary itself was edited. [http://holdinghandsis.gay/images/patched%20soundbank%20tool.7z](url)

**Comment by SubDrag** [comment]
I made these changes, however...

Please rebuild the source code yourself and submit merge requests.  You need any version of Visual Studio with MFC C++ - 2008 is easiest and probably cheapest, but it can work on any.  You may need to change targetver.h to later targets, beyond 0x400, since that is obsolete post Visual Studio 2008, and need to have DirectX installed, which is also on this github.  I am not maintaining these tools anymore in any serious fashion - this is why open source.

**Comment by SubDrag** [comment]
Thanks that would be helpful!  You will need to install directx sdk, point library paths to it (if different).  Install MFC C++.  Make sure you update targetver.h.  Setting running directory to main folder when running (so picks up ini). Should be that simple, more or less.
