### ISSUE TITLE
N64 MidiTool doesn't export every Midi in Perfect Dark

### ISSUE THREAD

**Issue by SoundTheHorn** [jombo23/N64-Tools#3]
After exporting all Midis for Perfect Dark, I noticed there were a lot of midis were missing. When I  looked through the tool's folders to see if I was able to fix this, I found, in gameconfig.ini, there were 119 listed Midis for Perfect Dark (U) (V1.1),
![gameconfigini](https://user-images.githubusercontent.com/15479144/52912934-64d1fa80-3286-11e9-86f1-d0c2e38df1c0.png)
 but, instead of all 119 listed in the .ini, I was only able to export 63 midis, which is very strange.
 ![miditool glitch](https://user-images.githubusercontent.com/15479144/52913147-08bca580-3289-11e9-8642-d78d57f74a1d.png)
I've tried the tool with other games, and I've seen that there is no cap of 63, so why this is happening with Perfect Dark specifically, I do not know.

**Comment by SubDrag** [comment]
This is a simple copy/paste bug.  It should say while (currentBinaryNumber <  0x77) under ProcessMidis for PerfectDark game, not, in N64MidiToolReader.cpp if someone wants to fix it...It was accidentally 0x3F.

**Comment by SoundTheHorn** [comment]
The issue has been fixed with the newest release. Thanks for the help!
