### ISSUE TITLE
Soundbank Tool exporting broken .dls files

### ISSUE THREAD

**Issue by beachbum811** [jombo23/N64-Tools#31]
Every rom I tried had this issue.
The exported samples seem to be mixed together, or several samples end-to-end, or something.
converting to .sf2 and using with the exported midis yields garbled noise.
I'm on a 64-bit Windows machine.
The preview button generates the audio flawlessly.
I therefore THINK the midis it exports are fine, but without the soundfont, I can't tell.
I used .n64 files and not .z64 files, and I tried fiddling with a bunch of settings to no effect.
[dls.zip](https://github.com/jombo23/N64-Tools/files/8026247/dls.zip)

**Comment by SubDrag** [comment]
Ugh you're right.  When did that happen...something's misaligned...I'll investigate.

**Comment by SubDrag** [comment]
Are you using Viena?  I wonder if Viena has a bug.  It's perfect in Awave Studio.

**Comment by SubDrag** [comment]
If you open in Awave, export to SF2, it's fine in Viena.  I think this has been broken in Viena for a long time.

**Comment by SubDrag** [comment]
Confirmed with the author of Viena.  This is a BUG in Viena.  "There was a bug introduced in 1.900 in August last year. This was not actually in relation to DLS files at all but had a side effect on DLS. "  It will be fixed in the next version of Viena out shortly.
