### ISSUE TITLE
Sound Tool V1.4 (rev. Jan. 31, 2022) crashes when loading Clay Figher 63 1/3 (USA) ROM

### ISSUE THREAD

**Issue by codentman** [jombo23/N64-Tools#32]
I'll first go to File -> Open Known Game -> Clay Fighter Sculptor's Cut to Cruis'n USA (U)(V1.1) -> Clay Fighter 63 1/3 (U).

Then I'll select the location of the ROM on my PC and open it. From here is where the app will crash.

Let me know if more info is needed. Thanks!

**Comment by SubDrag** [comment]
That's really strange, I cannot reproduce.  Are you sure it is a good ROM?  The latest is Feb 9, but it hasn't been changed.

**Comment by codentman** [comment]
I haven't tried getting another ROM. I'll do that and report back

**Comment by codentman** [comment]
> I haven't tried getting another ROM. I'll do that and report back

Once I got another ROM, it no longer crashed. Thanks for the suggestion!
