### ISSUE TITLE
Ocarina of Time missing midis

### ISSUE THREAD

**Issue by WheelmanMitch** [jombo23/N64-Tools#35]
Hi SubDrag, user "dj4uk6cjm" on HCS ( https://hcs64.com/mboard/forumlong.php?showthread=39165 ) released a MIDI rip of OoT but it's missing two pieces (Shooting Gallery, and Ganon's Organ (full version, it has a bunch of variations). I think they used SEQ64 to make them. I have no experience ripping midis with N64 MIDI tool, and the prospect of setting it up is a bit overwhelming. Can you help me find these MIDI files? If posting this here crosses a boundary I apologize.

**Comment by SubDrag** [comment]
I used the same exact original info from Seq64, but it seems like there aren't any missing midis.   I do see Ganon's Organ in the list though, but not Shooting Gallery, so maybe it's mislabeled or labeled differently?  You just basically open it up and export all midi.  If midis are actually missing and you know where they are please re-open this Issue and post the details.

Here is a tutorial online:
http://sheesh.us/tutorials/part-3-extracting-midi-files-from-any-n64-rom/
