### ISSUE TITLE
Ocarina of Time missing midis (Update)

### ISSUE THREAD

**Issue by WheelmanMitch** [jombo23/N64-Tools#36]
I installed N64 Midi Tool following the guide you linked me, located a V1.0 ROM of OoT, and extracted all midis to a folder. The Shooting Gallery midi was successfully exported, and Ganon's Organ was too, with each variation included in the same midi! I opened every single midi file in the old OoT midi rip I linked, and only one midi file does not open. It is called "Hyrule Field (Master).mid". Not sure what's wrong with it, but all other midis are correctly titled (except the missing oot files folder midis).

In the old rip I notice some notes are clipped, as in, they are so short you can't even see them sometimes. In the old midi rip, The Great Fairy Fountain music has clipped notes in the opening chords. But they are not clipped in the new rip I just did. Not sure why that is, or why Ganon's Organ was not exported completely with all notes.

Another strange thing I noticed is, some tracks like Zora's Domain (in the new rip) do not start at or include the beginning of the track. Any idea why these differences might have occurred? In any case I'm happy, I really wanted the full version of Ganon's Organ so I can transcribe it. Thanks for your help SubDrag! :)

**Comment by SubDrag** [comment]
They're exported differently. The old rip used Seq64 while at some point I wrote my own decoder. Also the new rip attempts to take all branches while I don't think Seq64 did, so you get variations but don't get songs that are normal. Also remember that this is really microcode with branches and such so it's not going to transcribe in a normal way. 

Are you saying notes should clip but don't?  I'm not quite sure what from what you said are actual issues?  Can you specifically list out the specific midis and what is problems on each. I may not be able to fix but can look.

**Comment by WheelmanMitch** [comment]
I was saying notes should not be clipped, but they are in the old rip in some songs. Great Fairy's Fountain and Zora's Domain have clipped notes in them. You need to open the MIDIs in MIDI Editor or the Music Animation Machine (MIDI player) to see what I am talking about. I was wondering if you had any idea why this would happen. Fairy's Fountain has clipped (very short) notes right at the start, so you can't miss them.

**Comment by SubDrag** [comment]
Not sure I understand. The old rip is from Seq64 which I don't support at all. There's a new version of Seq64 perhaps it's better.

**Comment by WheelmanMitch** [comment]
Here ya go: https://www.youtube.com/watch?v=sle-j4GrqlE

**Comment by SubDrag** [comment]
You're right, I grabbed Seq64 1.5 and can see what you're showing:
https://github.com/sauraen/seq64/releases

I don't know how to use version 2.X, somehow need get into these aseq/com formats.  Not clear to me how to do that. 

They are completely different implementations, so assuming mine is correct, and he still has that issue in 2.0, guess he has different timing or a problem.  Oddly though Seq64 is the standard for decompiled works (I'm told).

**Comment by WheelmanMitch** [comment]
Ahh it's not worth it to me to set all that up. N64 MIDI Tool was able to grab the two missing MIDI files I needed. My end goal is just to have good MIDI rips so I can transcribe the music perfectly! I happened to notice the note clipping because, I could hear notes in the game I couldn't see in the Seq64 MIDI. Only to then realize the notes WERE there, but were so tiny I could not see them.

N64 MIDI Tool appears not to have this problem at all. I can only fault the fact it doesn't play every track from the beginning. But I can use both the Seq64 and MIDI Tool rips together and get the full picture. Thanks a lot for your time SubDrag!

**Comment by SubDrag** [comment]
Btw - I got version 2.0 of Seq64 working, and it still has the problem (export the raw binary format from N64 Midi Tool and open in Seq64 2.0).  I have no idea why, quite strange if all the rest work fine, but he must have an issue or limitation somewhere or there is one of those programmatic branches/loops that he chooses not to take.   Seems a simpler music as well.

**Comment by SubDrag** [comment]
There are a couple "go to" in the song, that Seq64 maybe ignores?  Not sure...anyways at least you have something working.
