### ISSUE TITLE
N64SoundTool: Application cannot start because its side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by SKCro** [jombo23/N64-Tools#37]
Upon attempting to start the N64SoundListTool, this happens.
![image](https://user-images.githubusercontent.com/55817746/166713887-70c5dd37-5e73-4c1e-9648-863c667c4936.png)
I am on Windows 7 Service Pack 1, x64. It was updated in 2018 (probably), so it shouldn't have any issues running on Windows 7. Are there any prerequisites I forgot to install?

**Comment by SubDrag** [comment]
https://github.com/jombo23/N64-Tools/tree/master/Redistributables
