### ISSUE TITLE
Software closes when loading ROM (cannot find correct game).

### ISSUE THREAD

**Issue by HEXN3T** [jombo23/N64-Tools#38]
Trying to rip the SoundFont from F-Zero X. I cannot find the .sf2 file elsewhere, yet X style remixes are somewhat common. Trying to rip the sound font myself.

I looked through the list of games in the software and can't find F-Zero X, and therefore the software closes when I load the ROM. I highly doubt that no versions of F-Zero X are compatible; pretty sure I'm just missing something, unless the game actually is missing from the list (in this case, I am out of options).

EDIT: Found NUD-EFZJ-JPN. It's the Japanese eXpansion kit file. I downloaded the correct .n64 file, yet the software still crashes. At a dead end, now. I don't know what to do.

**Comment by SubDrag** [comment]
It's not there. No soundfont exists because music is stored as audio. It's not sequenced on N64. The N64 sound tool will rip it.
