### ISSUE TITLE
N64MIDITool Error when opening.

### ISSUE THREAD

**Issue by CandyPillager** [jombo23/N64-Tools#52]
Hello!
I just downloaded the N64 MIdi Tool and extracted the .7z file, I tried opening the N64MidiTool.exe file and I get an error saying: 
![image](https://user-images.githubusercontent.com/62050983/200923579-73423dc6-e9cc-4c00-8f74-707e1e909eb3.png)

How do I fix this? I don't have much knowledge of these github programs, and I would like to be able to use the N64 MIDI Tool.

**Comment by SubDrag** [comment]
Look at instructions, you need to install MFC C++ Redistributables.
Install all the redistributables here first before using anything: https://github.com/jombo23/N64-Tools/tree/master/Redistributables
