### ISSUE TITLE
[Star Fox 64 (J)] Can't rip bank 01

### ISSUE THREAD

**Issue by MrShiruba** [jombo23/N64-Tools#55]
I wanted to get the voices from the japanese version of the game. The game has english voices for the American and European voices whereas the japanese version has japanese voices.

Upon clicking "Rip All Sound Banks" on the japanese version (Star Fox 64 (J)), the application extracts every wav from all 31 banks except one : the bank 01 (BANK_01_INSTR_...). The thing is the bank 01 is successfully ripped when I extracted the voices from the English / USA version of the game (Star Fox 64 (U) (V1.1)). Choosing "SoundBank 01" and "Rip Sound Bank" doesn't output any file on the Japanese version (but outputs files for the english version).

I'd like to know if the problem is either the ROM (I've tried multiple) or the software.

**Comment by SubDrag** [comment]
Looks like a problem, I'll look into it.

**Comment by SubDrag** [comment]
Found the function - it's a very different format.  I'm investigating.

**Comment by MrShiruba** [comment]
Don't worry take your time I'm in no hurry. I was just curious and I perfectly understand N64 architecture can be annoying to deal with.
I don't know anyone else though who can be of any help.

**Comment by SubDrag** [comment]
Bank 01 now supported, enjoy, in last version uploaded to github.  It was a unique sound type, not seen anywhere else, or any other EAD game as far as I can tell.
