### ISSUE TITLE
N64SoundTool - CTL too big error

### ISSUE THREAD

**Issue by dkhagen** [jombo23/N64-Tools#56]
Trying to replace all of the SM64 sounds with custom sounds and receiving this error when partway through. It doesn't seem to happen consistently but I've noticed the tool also gets a lot less responsive after adding a lot of sounds. Is there something I'm missing? The sounds I'm replacing are all shorter than the original sounds to make sure no memory issues happen. Attached screenshot of error. This is likely user error so thanks in advance!

![soundtool_error](https://user-images.githubusercontent.com/11951650/215920366-6cabadf5-3b1c-4aeb-a5a9-c10b04263362.png)

**Comment by SubDrag** [comment]
Not user error. Just limitation of tool. It is generic and doesn't try and rearrange game rom. So you're limited to existing space. The best thing you can do is go incrementally, and feuds the same predictors and loop predictors so they are not different per sound. This saves a lot of ctl space though potentially lower quality sounds.

**Comment by dkhagen** [comment]
@SubDrag Thanks for the response, just to make sure I'm doing this correctly, I have to do the following steps for each sound?

1. Select a soundbank (e.g. 00)
2. Select an instrument (e.g. 0000)
3. Export both predictors and loop predictors
4. Import the new custom sound
5. Import both the original predictors and loop predictors
6. Inject in place
7. Move onto the next instrument

Just making sure I don't need to adjust any other values and confirming that the predictors are on a per instrument basis rather than soundbank level or something. Still trying to wrap my head around all this, thanks!

**Comment by SubDrag** [comment]
You want to share predictors - so click Import "16-bit VADPCM Wav (same pred).  This way the ctl won't grow as it will use existing predictors in slot.  If you need to you can also transfer predictors to another slot, but depending on what was used where, this may or may decrease file size.
