### ISSUE TITLE
Open a N64SoundTool Crash

### ISSUE THREAD

**Issue by soopadoopacoopa** [jombo23/N64-Tools#61]
![Crash n64sound](https://github.com/jombo23/N64-Tools/assets/66198303/e51a9d81-79d2-433d-a0e2-e5fe5315b876)
when i open the applacation it crashed

**Comment by SubDrag** [comment]
Need to install VS Redistributables
https://github.com/jombo23/N64-Tools/tree/master/Redistributables

**Comment by soopadoopacoopa** [comment]
oh... nevermind thanks for reminding me
