### ISSUE TITLE
[N64 Sound Bank Tool] Addition of "The New Tetris"?

### ISSUE THREAD

**Issue by ktg5** [jombo23/N64-Tools#64]
I checked the list of supported games and didn't see "The New Tetris" in there. Could it possibly be an addition to the list?

**Comment by SubDrag** [comment]
I believe it uses a tracker format so it's not going to be in a soundbank tool, but you can listen to the music in the other tools.

**Comment by ktg5** [comment]
Ah ok, thank you!
