### ISSUE TITLE
Exporting Maps and Textures from GoldenEye and Perfect Dark

### ISSUE THREAD

**Issue by DarylGraves** [jombo23/N64-Tools#74]
Hi Both,

Firstly, sorry to message you both out of the blue! I appreciate this isn't really a _N64-Tools_ thing directly and I'm asking you about something you worked on _literally over a decade ago_ but I found this repo, saw you've both contributed and are both still active on GitHub, so thought I'd try my luck!

I found a [website](https://noclip.website/) which allows you to view 3d video game levels in your browser - I was surprised no one has uploaded GoldenEye or Perfect Dark levels yet so I went down the rabbit-hole investigating how I could try and do this. Ultimately I came to the conclusion that it's outside of my current skillset, although I'd like to learn. You've both got _significantly_ further than me so I was hoping I could maybe get some tips on how I could approach this?

@L-Spiro - I found [this post](http://www.shootersforever.com/forums_message_boards/viewtopic.php?t=3650) and then [this post](https://tasvideos.org/Forum/Topics/5612) where you describe using MHS to periodically export the level coordinates from RAM into a text file. It's really impressive but I understand you weren't able to link the textures to the coordinates with this approach. I thought I could at least recreate what you did for the missing levels but I couldn't even figure out how you even determined what pointers were used for the coordinates? If I knew the first coordinate I suspect the rest are next to them but how do you even begin without any?

@SubDrag  - Today I stumbled across GoldenEye Setup Editor (not sure how I missed it before!) I was really excited to see that GoldenEye Setup Editor lets me view the map **with** the textures however I can't find a way to export the maps themselves, only the objects in the level. I was wondering (hoping) I may be missing something? Or if you recall how the map coordinates are linked to textures so I could potentially incorporate it into L-Spiro's method? 

This is what an export looked like in Blender:

![GoldenEye Obj](https://github.com/user-attachments/assets/749fb3b6-7c20-4c6f-9416-7b8ab3fface4)

Again, sorry for the random message but I've really enjoyed researching this and what you've both done is truly on another level, 

Thanks for any help you can give! I appreciate it was a long time ago though!!

Daryl

**Comment by L-Spiro** [comment]
Hello Daryl.

I have moved on to more effective approaches and I already have all of the
data you need.
I already tried to reply through GitHub but my message was too long, so if
you give me your e-mail I will forward my previous reply to you.


Regards,
L. Spiro

**Comment by DarylGraves** [comment]
Hi @L-Spiro

This sounds amazing, thank you! My email is d.graves88@outlook.com

Thanks!

Daryl
