### ISSUE TITLE
IGNORE THIS

### ISSUE THREAD

**Issue by I-am-the-Python-Tyrant** [jombo23/N64-Tools#77]
"ERROR: The application has failed to start because the side by side configuration is incorrect please see the application event log or use the command line sxstrace.exe tool for more detail" upon attempted use of n64 soundbank tool.
![soundbank error](https://github.com/user-attachments/assets/ad1d871b-5502-4c62-977b-32cdfca8e5bc)

**Comment by AshVPW** [comment]
Stop spamming me you shit ass website
